package vyo.technologies.living.optimizer.simscheduler.schedule;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: simschedular.proto

public final class ScheduleProto {
  private ScheduleProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ScheduleOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Schedule)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string personName = 1;</code>
     * @return The personName.
     */
    java.lang.String getPersonName();
    /**
     * <code>string personName = 1;</code>
     * @return The bytes for personName.
     */
    com.google.protobuf.ByteString
        getPersonNameBytes();

    /**
     * <code>string scheduleRevision = 2;</code>
     * @return The scheduleRevision.
     */
    java.lang.String getScheduleRevision();
    /**
     * <code>string scheduleRevision = 2;</code>
     * @return The bytes for scheduleRevision.
     */
    com.google.protobuf.ByteString
        getScheduleRevisionBytes();

    /**
     * <code>repeated .ScheduleSlot slots = 3;</code>
     */
    java.util.List<ScheduleProto.ScheduleSlot> 
        getSlotsList();
    /**
     * <code>repeated .ScheduleSlot slots = 3;</code>
     */
    ScheduleProto.ScheduleSlot getSlots(int index);
    /**
     * <code>repeated .ScheduleSlot slots = 3;</code>
     */
    int getSlotsCount();
    /**
     * <code>repeated .ScheduleSlot slots = 3;</code>
     */
    java.util.List<? extends ScheduleProto.ScheduleSlotOrBuilder> 
        getSlotsOrBuilderList();
    /**
     * <code>repeated .ScheduleSlot slots = 3;</code>
     */
    ScheduleProto.ScheduleSlotOrBuilder getSlotsOrBuilder(
        int index);
  }
  /**
   * <pre>
   *Unsure if efficent, but gonna ignore the urge to make more "proper"
   * </pre>
   *
   * Protobuf type {@code Schedule}
   */
  public static final class Schedule extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Schedule)
      ScheduleOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Schedule.newBuilder() to construct.
    private Schedule(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Schedule() {
      personName_ = "";
      scheduleRevision_ = "";
      slots_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Schedule();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Schedule(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              personName_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              scheduleRevision_ = s;
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                slots_ = new java.util.ArrayList<ScheduleProto.ScheduleSlot>();
                mutable_bitField0_ |= 0x00000001;
              }
              slots_.add(
                  input.readMessage(ScheduleProto.ScheduleSlot.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          slots_ = java.util.Collections.unmodifiableList(slots_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ScheduleProto.internal_static_Schedule_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ScheduleProto.internal_static_Schedule_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ScheduleProto.Schedule.class, ScheduleProto.Schedule.Builder.class);
    }

    public static final int PERSONNAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object personName_;
    /**
     * <code>string personName = 1;</code>
     * @return The personName.
     */
    @java.lang.Override
    public java.lang.String getPersonName() {
      java.lang.Object ref = personName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        personName_ = s;
        return s;
      }
    }
    /**
     * <code>string personName = 1;</code>
     * @return The bytes for personName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPersonNameBytes() {
      java.lang.Object ref = personName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        personName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SCHEDULEREVISION_FIELD_NUMBER = 2;
    private volatile java.lang.Object scheduleRevision_;
    /**
     * <code>string scheduleRevision = 2;</code>
     * @return The scheduleRevision.
     */
    @java.lang.Override
    public java.lang.String getScheduleRevision() {
      java.lang.Object ref = scheduleRevision_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        scheduleRevision_ = s;
        return s;
      }
    }
    /**
     * <code>string scheduleRevision = 2;</code>
     * @return The bytes for scheduleRevision.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getScheduleRevisionBytes() {
      java.lang.Object ref = scheduleRevision_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        scheduleRevision_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SLOTS_FIELD_NUMBER = 3;
    private java.util.List<ScheduleProto.ScheduleSlot> slots_;
    /**
     * <code>repeated .ScheduleSlot slots = 3;</code>
     */
    @java.lang.Override
    public java.util.List<ScheduleProto.ScheduleSlot> getSlotsList() {
      return slots_;
    }
    /**
     * <code>repeated .ScheduleSlot slots = 3;</code>
     */
    @java.lang.Override
    public java.util.List<? extends ScheduleProto.ScheduleSlotOrBuilder> 
        getSlotsOrBuilderList() {
      return slots_;
    }
    /**
     * <code>repeated .ScheduleSlot slots = 3;</code>
     */
    @java.lang.Override
    public int getSlotsCount() {
      return slots_.size();
    }
    /**
     * <code>repeated .ScheduleSlot slots = 3;</code>
     */
    @java.lang.Override
    public ScheduleProto.ScheduleSlot getSlots(int index) {
      return slots_.get(index);
    }
    /**
     * <code>repeated .ScheduleSlot slots = 3;</code>
     */
    @java.lang.Override
    public ScheduleProto.ScheduleSlotOrBuilder getSlotsOrBuilder(
        int index) {
      return slots_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(personName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, personName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(scheduleRevision_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, scheduleRevision_);
      }
      for (int i = 0; i < slots_.size(); i++) {
        output.writeMessage(3, slots_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(personName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, personName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(scheduleRevision_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, scheduleRevision_);
      }
      for (int i = 0; i < slots_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, slots_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ScheduleProto.Schedule)) {
        return super.equals(obj);
      }
      ScheduleProto.Schedule other = (ScheduleProto.Schedule) obj;

      if (!getPersonName()
          .equals(other.getPersonName())) return false;
      if (!getScheduleRevision()
          .equals(other.getScheduleRevision())) return false;
      if (!getSlotsList()
          .equals(other.getSlotsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PERSONNAME_FIELD_NUMBER;
      hash = (53 * hash) + getPersonName().hashCode();
      hash = (37 * hash) + SCHEDULEREVISION_FIELD_NUMBER;
      hash = (53 * hash) + getScheduleRevision().hashCode();
      if (getSlotsCount() > 0) {
        hash = (37 * hash) + SLOTS_FIELD_NUMBER;
        hash = (53 * hash) + getSlotsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ScheduleProto.Schedule parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ScheduleProto.Schedule parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ScheduleProto.Schedule parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ScheduleProto.Schedule parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ScheduleProto.Schedule parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ScheduleProto.Schedule parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ScheduleProto.Schedule parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ScheduleProto.Schedule parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ScheduleProto.Schedule parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ScheduleProto.Schedule parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ScheduleProto.Schedule parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ScheduleProto.Schedule parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ScheduleProto.Schedule prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *Unsure if efficent, but gonna ignore the urge to make more "proper"
     * </pre>
     *
     * Protobuf type {@code Schedule}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Schedule)
        ScheduleProto.ScheduleOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ScheduleProto.internal_static_Schedule_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ScheduleProto.internal_static_Schedule_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ScheduleProto.Schedule.class, ScheduleProto.Schedule.Builder.class);
      }

      // Construct using ScheduleProto.Schedule.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getSlotsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        personName_ = "";

        scheduleRevision_ = "";

        if (slotsBuilder_ == null) {
          slots_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          slotsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ScheduleProto.internal_static_Schedule_descriptor;
      }

      @java.lang.Override
      public ScheduleProto.Schedule getDefaultInstanceForType() {
        return ScheduleProto.Schedule.getDefaultInstance();
      }

      @java.lang.Override
      public ScheduleProto.Schedule build() {
        ScheduleProto.Schedule result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ScheduleProto.Schedule buildPartial() {
        ScheduleProto.Schedule result = new ScheduleProto.Schedule(this);
        int from_bitField0_ = bitField0_;
        result.personName_ = personName_;
        result.scheduleRevision_ = scheduleRevision_;
        if (slotsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            slots_ = java.util.Collections.unmodifiableList(slots_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.slots_ = slots_;
        } else {
          result.slots_ = slotsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ScheduleProto.Schedule) {
          return mergeFrom((ScheduleProto.Schedule)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ScheduleProto.Schedule other) {
        if (other == ScheduleProto.Schedule.getDefaultInstance()) return this;
        if (!other.getPersonName().isEmpty()) {
          personName_ = other.personName_;
          onChanged();
        }
        if (!other.getScheduleRevision().isEmpty()) {
          scheduleRevision_ = other.scheduleRevision_;
          onChanged();
        }
        if (slotsBuilder_ == null) {
          if (!other.slots_.isEmpty()) {
            if (slots_.isEmpty()) {
              slots_ = other.slots_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureSlotsIsMutable();
              slots_.addAll(other.slots_);
            }
            onChanged();
          }
        } else {
          if (!other.slots_.isEmpty()) {
            if (slotsBuilder_.isEmpty()) {
              slotsBuilder_.dispose();
              slotsBuilder_ = null;
              slots_ = other.slots_;
              bitField0_ = (bitField0_ & ~0x00000001);
              slotsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getSlotsFieldBuilder() : null;
            } else {
              slotsBuilder_.addAllMessages(other.slots_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ScheduleProto.Schedule parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ScheduleProto.Schedule) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object personName_ = "";
      /**
       * <code>string personName = 1;</code>
       * @return The personName.
       */
      public java.lang.String getPersonName() {
        java.lang.Object ref = personName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          personName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string personName = 1;</code>
       * @return The bytes for personName.
       */
      public com.google.protobuf.ByteString
          getPersonNameBytes() {
        java.lang.Object ref = personName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          personName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string personName = 1;</code>
       * @param value The personName to set.
       * @return This builder for chaining.
       */
      public Builder setPersonName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        personName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string personName = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPersonName() {
        
        personName_ = getDefaultInstance().getPersonName();
        onChanged();
        return this;
      }
      /**
       * <code>string personName = 1;</code>
       * @param value The bytes for personName to set.
       * @return This builder for chaining.
       */
      public Builder setPersonNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        personName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object scheduleRevision_ = "";
      /**
       * <code>string scheduleRevision = 2;</code>
       * @return The scheduleRevision.
       */
      public java.lang.String getScheduleRevision() {
        java.lang.Object ref = scheduleRevision_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          scheduleRevision_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string scheduleRevision = 2;</code>
       * @return The bytes for scheduleRevision.
       */
      public com.google.protobuf.ByteString
          getScheduleRevisionBytes() {
        java.lang.Object ref = scheduleRevision_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          scheduleRevision_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string scheduleRevision = 2;</code>
       * @param value The scheduleRevision to set.
       * @return This builder for chaining.
       */
      public Builder setScheduleRevision(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        scheduleRevision_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string scheduleRevision = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearScheduleRevision() {
        
        scheduleRevision_ = getDefaultInstance().getScheduleRevision();
        onChanged();
        return this;
      }
      /**
       * <code>string scheduleRevision = 2;</code>
       * @param value The bytes for scheduleRevision to set.
       * @return This builder for chaining.
       */
      public Builder setScheduleRevisionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        scheduleRevision_ = value;
        onChanged();
        return this;
      }

      private java.util.List<ScheduleProto.ScheduleSlot> slots_ =
        java.util.Collections.emptyList();
      private void ensureSlotsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          slots_ = new java.util.ArrayList<ScheduleProto.ScheduleSlot>(slots_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          ScheduleProto.ScheduleSlot, ScheduleProto.ScheduleSlot.Builder, ScheduleProto.ScheduleSlotOrBuilder> slotsBuilder_;

      /**
       * <code>repeated .ScheduleSlot slots = 3;</code>
       */
      public java.util.List<ScheduleProto.ScheduleSlot> getSlotsList() {
        if (slotsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(slots_);
        } else {
          return slotsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .ScheduleSlot slots = 3;</code>
       */
      public int getSlotsCount() {
        if (slotsBuilder_ == null) {
          return slots_.size();
        } else {
          return slotsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .ScheduleSlot slots = 3;</code>
       */
      public ScheduleProto.ScheduleSlot getSlots(int index) {
        if (slotsBuilder_ == null) {
          return slots_.get(index);
        } else {
          return slotsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .ScheduleSlot slots = 3;</code>
       */
      public Builder setSlots(
          int index, ScheduleProto.ScheduleSlot value) {
        if (slotsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSlotsIsMutable();
          slots_.set(index, value);
          onChanged();
        } else {
          slotsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ScheduleSlot slots = 3;</code>
       */
      public Builder setSlots(
          int index, ScheduleProto.ScheduleSlot.Builder builderForValue) {
        if (slotsBuilder_ == null) {
          ensureSlotsIsMutable();
          slots_.set(index, builderForValue.build());
          onChanged();
        } else {
          slotsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ScheduleSlot slots = 3;</code>
       */
      public Builder addSlots(ScheduleProto.ScheduleSlot value) {
        if (slotsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSlotsIsMutable();
          slots_.add(value);
          onChanged();
        } else {
          slotsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .ScheduleSlot slots = 3;</code>
       */
      public Builder addSlots(
          int index, ScheduleProto.ScheduleSlot value) {
        if (slotsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSlotsIsMutable();
          slots_.add(index, value);
          onChanged();
        } else {
          slotsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ScheduleSlot slots = 3;</code>
       */
      public Builder addSlots(
          ScheduleProto.ScheduleSlot.Builder builderForValue) {
        if (slotsBuilder_ == null) {
          ensureSlotsIsMutable();
          slots_.add(builderForValue.build());
          onChanged();
        } else {
          slotsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ScheduleSlot slots = 3;</code>
       */
      public Builder addSlots(
          int index, ScheduleProto.ScheduleSlot.Builder builderForValue) {
        if (slotsBuilder_ == null) {
          ensureSlotsIsMutable();
          slots_.add(index, builderForValue.build());
          onChanged();
        } else {
          slotsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ScheduleSlot slots = 3;</code>
       */
      public Builder addAllSlots(
          java.lang.Iterable<? extends ScheduleProto.ScheduleSlot> values) {
        if (slotsBuilder_ == null) {
          ensureSlotsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, slots_);
          onChanged();
        } else {
          slotsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .ScheduleSlot slots = 3;</code>
       */
      public Builder clearSlots() {
        if (slotsBuilder_ == null) {
          slots_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          slotsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .ScheduleSlot slots = 3;</code>
       */
      public Builder removeSlots(int index) {
        if (slotsBuilder_ == null) {
          ensureSlotsIsMutable();
          slots_.remove(index);
          onChanged();
        } else {
          slotsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .ScheduleSlot slots = 3;</code>
       */
      public ScheduleProto.ScheduleSlot.Builder getSlotsBuilder(
          int index) {
        return getSlotsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .ScheduleSlot slots = 3;</code>
       */
      public ScheduleProto.ScheduleSlotOrBuilder getSlotsOrBuilder(
          int index) {
        if (slotsBuilder_ == null) {
          return slots_.get(index);  } else {
          return slotsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .ScheduleSlot slots = 3;</code>
       */
      public java.util.List<? extends ScheduleProto.ScheduleSlotOrBuilder> 
           getSlotsOrBuilderList() {
        if (slotsBuilder_ != null) {
          return slotsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(slots_);
        }
      }
      /**
       * <code>repeated .ScheduleSlot slots = 3;</code>
       */
      public ScheduleProto.ScheduleSlot.Builder addSlotsBuilder() {
        return getSlotsFieldBuilder().addBuilder(
            ScheduleProto.ScheduleSlot.getDefaultInstance());
      }
      /**
       * <code>repeated .ScheduleSlot slots = 3;</code>
       */
      public ScheduleProto.ScheduleSlot.Builder addSlotsBuilder(
          int index) {
        return getSlotsFieldBuilder().addBuilder(
            index, ScheduleProto.ScheduleSlot.getDefaultInstance());
      }
      /**
       * <code>repeated .ScheduleSlot slots = 3;</code>
       */
      public java.util.List<ScheduleProto.ScheduleSlot.Builder> 
           getSlotsBuilderList() {
        return getSlotsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          ScheduleProto.ScheduleSlot, ScheduleProto.ScheduleSlot.Builder, ScheduleProto.ScheduleSlotOrBuilder> 
          getSlotsFieldBuilder() {
        if (slotsBuilder_ == null) {
          slotsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              ScheduleProto.ScheduleSlot, ScheduleProto.ScheduleSlot.Builder, ScheduleProto.ScheduleSlotOrBuilder>(
                  slots_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          slots_ = null;
        }
        return slotsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Schedule)
    }

    // @@protoc_insertion_point(class_scope:Schedule)
    private static final ScheduleProto.Schedule DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ScheduleProto.Schedule();
    }

    public static ScheduleProto.Schedule getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Schedule>
        PARSER = new com.google.protobuf.AbstractParser<Schedule>() {
      @java.lang.Override
      public Schedule parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Schedule(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Schedule> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Schedule> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ScheduleProto.Schedule getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ScheduleSlotOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ScheduleSlot)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 ID = 1;</code>
     * @return The iD.
     */
    int getID();

    /**
     * <code>string slotName = 2;</code>
     * @return The slotName.
     */
    java.lang.String getSlotName();
    /**
     * <code>string slotName = 2;</code>
     * @return The bytes for slotName.
     */
    com.google.protobuf.ByteString
        getSlotNameBytes();

    /**
     * <code>string slotDesc = 3;</code>
     * @return The slotDesc.
     */
    java.lang.String getSlotDesc();
    /**
     * <code>string slotDesc = 3;</code>
     * @return The bytes for slotDesc.
     */
    com.google.protobuf.ByteString
        getSlotDescBytes();

    /**
     * <code>.google.protobuf.Timestamp startTime = 4;</code>
     * @return Whether the startTime field is set.
     */
    boolean hasStartTime();
    /**
     * <code>.google.protobuf.Timestamp startTime = 4;</code>
     * @return The startTime.
     */
    com.google.protobuf.Timestamp getStartTime();
    /**
     * <code>.google.protobuf.Timestamp startTime = 4;</code>
     */
    com.google.protobuf.TimestampOrBuilder getStartTimeOrBuilder();

    /**
     * <code>.google.protobuf.Timestamp endTime = 5;</code>
     * @return Whether the endTime field is set.
     */
    boolean hasEndTime();
    /**
     * <code>.google.protobuf.Timestamp endTime = 5;</code>
     * @return The endTime.
     */
    com.google.protobuf.Timestamp getEndTime();
    /**
     * <code>.google.protobuf.Timestamp endTime = 5;</code>
     */
    com.google.protobuf.TimestampOrBuilder getEndTimeOrBuilder();

    /**
     * <code>.ScheduleSlot.Day day = 6;</code>
     * @return The enum numeric value on the wire for day.
     */
    int getDayValue();
    /**
     * <code>.ScheduleSlot.Day day = 6;</code>
     * @return The day.
     */
    ScheduleProto.ScheduleSlot.Day getDay();
  }
  /**
   * Protobuf type {@code ScheduleSlot}
   */
  public static final class ScheduleSlot extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ScheduleSlot)
      ScheduleSlotOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ScheduleSlot.newBuilder() to construct.
    private ScheduleSlot(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ScheduleSlot() {
      slotName_ = "";
      slotDesc_ = "";
      day_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ScheduleSlot();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ScheduleSlot(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              iD_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              slotName_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              slotDesc_ = s;
              break;
            }
            case 34: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (startTime_ != null) {
                subBuilder = startTime_.toBuilder();
              }
              startTime_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(startTime_);
                startTime_ = subBuilder.buildPartial();
              }

              break;
            }
            case 42: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (endTime_ != null) {
                subBuilder = endTime_.toBuilder();
              }
              endTime_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(endTime_);
                endTime_ = subBuilder.buildPartial();
              }

              break;
            }
            case 48: {
              int rawValue = input.readEnum();

              day_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ScheduleProto.internal_static_ScheduleSlot_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ScheduleProto.internal_static_ScheduleSlot_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ScheduleProto.ScheduleSlot.class, ScheduleProto.ScheduleSlot.Builder.class);
    }

    /**
     * Protobuf enum {@code ScheduleSlot.Day}
     */
    public enum Day
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>MON = 0;</code>
       */
      MON(0),
      /**
       * <code>TUE = 1;</code>
       */
      TUE(1),
      /**
       * <code>WED = 2;</code>
       */
      WED(2),
      /**
       * <code>THU = 3;</code>
       */
      THU(3),
      /**
       * <code>FRI = 4;</code>
       */
      FRI(4),
      /**
       * <code>SAT = 5;</code>
       */
      SAT(5),
      /**
       * <code>SUN = 6;</code>
       */
      SUN(6),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>MON = 0;</code>
       */
      public static final int MON_VALUE = 0;
      /**
       * <code>TUE = 1;</code>
       */
      public static final int TUE_VALUE = 1;
      /**
       * <code>WED = 2;</code>
       */
      public static final int WED_VALUE = 2;
      /**
       * <code>THU = 3;</code>
       */
      public static final int THU_VALUE = 3;
      /**
       * <code>FRI = 4;</code>
       */
      public static final int FRI_VALUE = 4;
      /**
       * <code>SAT = 5;</code>
       */
      public static final int SAT_VALUE = 5;
      /**
       * <code>SUN = 6;</code>
       */
      public static final int SUN_VALUE = 6;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Day valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static Day forNumber(int value) {
        switch (value) {
          case 0: return MON;
          case 1: return TUE;
          case 2: return WED;
          case 3: return THU;
          case 4: return FRI;
          case 5: return SAT;
          case 6: return SUN;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Day>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Day> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Day>() {
              public Day findValueByNumber(int number) {
                return Day.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return ScheduleProto.ScheduleSlot.getDescriptor().getEnumTypes().get(0);
      }

      private static final Day[] VALUES = values();

      public static Day valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Day(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:ScheduleSlot.Day)
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int iD_;
    /**
     * <code>int32 ID = 1;</code>
     * @return The iD.
     */
    @java.lang.Override
    public int getID() {
      return iD_;
    }

    public static final int SLOTNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object slotName_;
    /**
     * <code>string slotName = 2;</code>
     * @return The slotName.
     */
    @java.lang.Override
    public java.lang.String getSlotName() {
      java.lang.Object ref = slotName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        slotName_ = s;
        return s;
      }
    }
    /**
     * <code>string slotName = 2;</code>
     * @return The bytes for slotName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSlotNameBytes() {
      java.lang.Object ref = slotName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        slotName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SLOTDESC_FIELD_NUMBER = 3;
    private volatile java.lang.Object slotDesc_;
    /**
     * <code>string slotDesc = 3;</code>
     * @return The slotDesc.
     */
    @java.lang.Override
    public java.lang.String getSlotDesc() {
      java.lang.Object ref = slotDesc_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        slotDesc_ = s;
        return s;
      }
    }
    /**
     * <code>string slotDesc = 3;</code>
     * @return The bytes for slotDesc.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSlotDescBytes() {
      java.lang.Object ref = slotDesc_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        slotDesc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STARTTIME_FIELD_NUMBER = 4;
    private com.google.protobuf.Timestamp startTime_;
    /**
     * <code>.google.protobuf.Timestamp startTime = 4;</code>
     * @return Whether the startTime field is set.
     */
    @java.lang.Override
    public boolean hasStartTime() {
      return startTime_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp startTime = 4;</code>
     * @return The startTime.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getStartTime() {
      return startTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : startTime_;
    }
    /**
     * <code>.google.protobuf.Timestamp startTime = 4;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getStartTimeOrBuilder() {
      return getStartTime();
    }

    public static final int ENDTIME_FIELD_NUMBER = 5;
    private com.google.protobuf.Timestamp endTime_;
    /**
     * <code>.google.protobuf.Timestamp endTime = 5;</code>
     * @return Whether the endTime field is set.
     */
    @java.lang.Override
    public boolean hasEndTime() {
      return endTime_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp endTime = 5;</code>
     * @return The endTime.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getEndTime() {
      return endTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : endTime_;
    }
    /**
     * <code>.google.protobuf.Timestamp endTime = 5;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getEndTimeOrBuilder() {
      return getEndTime();
    }

    public static final int DAY_FIELD_NUMBER = 6;
    private int day_;
    /**
     * <code>.ScheduleSlot.Day day = 6;</code>
     * @return The enum numeric value on the wire for day.
     */
    @java.lang.Override public int getDayValue() {
      return day_;
    }
    /**
     * <code>.ScheduleSlot.Day day = 6;</code>
     * @return The day.
     */
    @java.lang.Override public ScheduleProto.ScheduleSlot.Day getDay() {
      @SuppressWarnings("deprecation")
      ScheduleProto.ScheduleSlot.Day result = ScheduleProto.ScheduleSlot.Day.valueOf(day_);
      return result == null ? ScheduleProto.ScheduleSlot.Day.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (iD_ != 0) {
        output.writeInt32(1, iD_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(slotName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, slotName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(slotDesc_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, slotDesc_);
      }
      if (startTime_ != null) {
        output.writeMessage(4, getStartTime());
      }
      if (endTime_ != null) {
        output.writeMessage(5, getEndTime());
      }
      if (day_ != ScheduleProto.ScheduleSlot.Day.MON.getNumber()) {
        output.writeEnum(6, day_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (iD_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, iD_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(slotName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, slotName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(slotDesc_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, slotDesc_);
      }
      if (startTime_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getStartTime());
      }
      if (endTime_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getEndTime());
      }
      if (day_ != ScheduleProto.ScheduleSlot.Day.MON.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(6, day_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ScheduleProto.ScheduleSlot)) {
        return super.equals(obj);
      }
      ScheduleProto.ScheduleSlot other = (ScheduleProto.ScheduleSlot) obj;

      if (getID()
          != other.getID()) return false;
      if (!getSlotName()
          .equals(other.getSlotName())) return false;
      if (!getSlotDesc()
          .equals(other.getSlotDesc())) return false;
      if (hasStartTime() != other.hasStartTime()) return false;
      if (hasStartTime()) {
        if (!getStartTime()
            .equals(other.getStartTime())) return false;
      }
      if (hasEndTime() != other.hasEndTime()) return false;
      if (hasEndTime()) {
        if (!getEndTime()
            .equals(other.getEndTime())) return false;
      }
      if (day_ != other.day_) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getID();
      hash = (37 * hash) + SLOTNAME_FIELD_NUMBER;
      hash = (53 * hash) + getSlotName().hashCode();
      hash = (37 * hash) + SLOTDESC_FIELD_NUMBER;
      hash = (53 * hash) + getSlotDesc().hashCode();
      if (hasStartTime()) {
        hash = (37 * hash) + STARTTIME_FIELD_NUMBER;
        hash = (53 * hash) + getStartTime().hashCode();
      }
      if (hasEndTime()) {
        hash = (37 * hash) + ENDTIME_FIELD_NUMBER;
        hash = (53 * hash) + getEndTime().hashCode();
      }
      hash = (37 * hash) + DAY_FIELD_NUMBER;
      hash = (53 * hash) + day_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ScheduleProto.ScheduleSlot parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ScheduleProto.ScheduleSlot parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ScheduleProto.ScheduleSlot parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ScheduleProto.ScheduleSlot parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ScheduleProto.ScheduleSlot parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ScheduleProto.ScheduleSlot parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ScheduleProto.ScheduleSlot parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ScheduleProto.ScheduleSlot parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ScheduleProto.ScheduleSlot parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ScheduleProto.ScheduleSlot parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ScheduleProto.ScheduleSlot parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ScheduleProto.ScheduleSlot parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ScheduleProto.ScheduleSlot prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ScheduleSlot}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ScheduleSlot)
        ScheduleProto.ScheduleSlotOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ScheduleProto.internal_static_ScheduleSlot_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ScheduleProto.internal_static_ScheduleSlot_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ScheduleProto.ScheduleSlot.class, ScheduleProto.ScheduleSlot.Builder.class);
      }

      // Construct using ScheduleProto.ScheduleSlot.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        iD_ = 0;

        slotName_ = "";

        slotDesc_ = "";

        if (startTimeBuilder_ == null) {
          startTime_ = null;
        } else {
          startTime_ = null;
          startTimeBuilder_ = null;
        }
        if (endTimeBuilder_ == null) {
          endTime_ = null;
        } else {
          endTime_ = null;
          endTimeBuilder_ = null;
        }
        day_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ScheduleProto.internal_static_ScheduleSlot_descriptor;
      }

      @java.lang.Override
      public ScheduleProto.ScheduleSlot getDefaultInstanceForType() {
        return ScheduleProto.ScheduleSlot.getDefaultInstance();
      }

      @java.lang.Override
      public ScheduleProto.ScheduleSlot build() {
        ScheduleProto.ScheduleSlot result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ScheduleProto.ScheduleSlot buildPartial() {
        ScheduleProto.ScheduleSlot result = new ScheduleProto.ScheduleSlot(this);
        result.iD_ = iD_;
        result.slotName_ = slotName_;
        result.slotDesc_ = slotDesc_;
        if (startTimeBuilder_ == null) {
          result.startTime_ = startTime_;
        } else {
          result.startTime_ = startTimeBuilder_.build();
        }
        if (endTimeBuilder_ == null) {
          result.endTime_ = endTime_;
        } else {
          result.endTime_ = endTimeBuilder_.build();
        }
        result.day_ = day_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ScheduleProto.ScheduleSlot) {
          return mergeFrom((ScheduleProto.ScheduleSlot)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ScheduleProto.ScheduleSlot other) {
        if (other == ScheduleProto.ScheduleSlot.getDefaultInstance()) return this;
        if (other.getID() != 0) {
          setID(other.getID());
        }
        if (!other.getSlotName().isEmpty()) {
          slotName_ = other.slotName_;
          onChanged();
        }
        if (!other.getSlotDesc().isEmpty()) {
          slotDesc_ = other.slotDesc_;
          onChanged();
        }
        if (other.hasStartTime()) {
          mergeStartTime(other.getStartTime());
        }
        if (other.hasEndTime()) {
          mergeEndTime(other.getEndTime());
        }
        if (other.day_ != 0) {
          setDayValue(other.getDayValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ScheduleProto.ScheduleSlot parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ScheduleProto.ScheduleSlot) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int iD_ ;
      /**
       * <code>int32 ID = 1;</code>
       * @return The iD.
       */
      @java.lang.Override
      public int getID() {
        return iD_;
      }
      /**
       * <code>int32 ID = 1;</code>
       * @param value The iD to set.
       * @return This builder for chaining.
       */
      public Builder setID(int value) {
        
        iD_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 ID = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearID() {
        
        iD_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object slotName_ = "";
      /**
       * <code>string slotName = 2;</code>
       * @return The slotName.
       */
      public java.lang.String getSlotName() {
        java.lang.Object ref = slotName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          slotName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string slotName = 2;</code>
       * @return The bytes for slotName.
       */
      public com.google.protobuf.ByteString
          getSlotNameBytes() {
        java.lang.Object ref = slotName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          slotName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string slotName = 2;</code>
       * @param value The slotName to set.
       * @return This builder for chaining.
       */
      public Builder setSlotName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        slotName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string slotName = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSlotName() {
        
        slotName_ = getDefaultInstance().getSlotName();
        onChanged();
        return this;
      }
      /**
       * <code>string slotName = 2;</code>
       * @param value The bytes for slotName to set.
       * @return This builder for chaining.
       */
      public Builder setSlotNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        slotName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object slotDesc_ = "";
      /**
       * <code>string slotDesc = 3;</code>
       * @return The slotDesc.
       */
      public java.lang.String getSlotDesc() {
        java.lang.Object ref = slotDesc_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          slotDesc_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string slotDesc = 3;</code>
       * @return The bytes for slotDesc.
       */
      public com.google.protobuf.ByteString
          getSlotDescBytes() {
        java.lang.Object ref = slotDesc_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          slotDesc_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string slotDesc = 3;</code>
       * @param value The slotDesc to set.
       * @return This builder for chaining.
       */
      public Builder setSlotDesc(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        slotDesc_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string slotDesc = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSlotDesc() {
        
        slotDesc_ = getDefaultInstance().getSlotDesc();
        onChanged();
        return this;
      }
      /**
       * <code>string slotDesc = 3;</code>
       * @param value The bytes for slotDesc to set.
       * @return This builder for chaining.
       */
      public Builder setSlotDescBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        slotDesc_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp startTime_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> startTimeBuilder_;
      /**
       * <code>.google.protobuf.Timestamp startTime = 4;</code>
       * @return Whether the startTime field is set.
       */
      public boolean hasStartTime() {
        return startTimeBuilder_ != null || startTime_ != null;
      }
      /**
       * <code>.google.protobuf.Timestamp startTime = 4;</code>
       * @return The startTime.
       */
      public com.google.protobuf.Timestamp getStartTime() {
        if (startTimeBuilder_ == null) {
          return startTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : startTime_;
        } else {
          return startTimeBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp startTime = 4;</code>
       */
      public Builder setStartTime(com.google.protobuf.Timestamp value) {
        if (startTimeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          startTime_ = value;
          onChanged();
        } else {
          startTimeBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp startTime = 4;</code>
       */
      public Builder setStartTime(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (startTimeBuilder_ == null) {
          startTime_ = builderForValue.build();
          onChanged();
        } else {
          startTimeBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp startTime = 4;</code>
       */
      public Builder mergeStartTime(com.google.protobuf.Timestamp value) {
        if (startTimeBuilder_ == null) {
          if (startTime_ != null) {
            startTime_ =
              com.google.protobuf.Timestamp.newBuilder(startTime_).mergeFrom(value).buildPartial();
          } else {
            startTime_ = value;
          }
          onChanged();
        } else {
          startTimeBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp startTime = 4;</code>
       */
      public Builder clearStartTime() {
        if (startTimeBuilder_ == null) {
          startTime_ = null;
          onChanged();
        } else {
          startTime_ = null;
          startTimeBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp startTime = 4;</code>
       */
      public com.google.protobuf.Timestamp.Builder getStartTimeBuilder() {
        
        onChanged();
        return getStartTimeFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp startTime = 4;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getStartTimeOrBuilder() {
        if (startTimeBuilder_ != null) {
          return startTimeBuilder_.getMessageOrBuilder();
        } else {
          return startTime_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : startTime_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp startTime = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getStartTimeFieldBuilder() {
        if (startTimeBuilder_ == null) {
          startTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getStartTime(),
                  getParentForChildren(),
                  isClean());
          startTime_ = null;
        }
        return startTimeBuilder_;
      }

      private com.google.protobuf.Timestamp endTime_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> endTimeBuilder_;
      /**
       * <code>.google.protobuf.Timestamp endTime = 5;</code>
       * @return Whether the endTime field is set.
       */
      public boolean hasEndTime() {
        return endTimeBuilder_ != null || endTime_ != null;
      }
      /**
       * <code>.google.protobuf.Timestamp endTime = 5;</code>
       * @return The endTime.
       */
      public com.google.protobuf.Timestamp getEndTime() {
        if (endTimeBuilder_ == null) {
          return endTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : endTime_;
        } else {
          return endTimeBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp endTime = 5;</code>
       */
      public Builder setEndTime(com.google.protobuf.Timestamp value) {
        if (endTimeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          endTime_ = value;
          onChanged();
        } else {
          endTimeBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp endTime = 5;</code>
       */
      public Builder setEndTime(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (endTimeBuilder_ == null) {
          endTime_ = builderForValue.build();
          onChanged();
        } else {
          endTimeBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp endTime = 5;</code>
       */
      public Builder mergeEndTime(com.google.protobuf.Timestamp value) {
        if (endTimeBuilder_ == null) {
          if (endTime_ != null) {
            endTime_ =
              com.google.protobuf.Timestamp.newBuilder(endTime_).mergeFrom(value).buildPartial();
          } else {
            endTime_ = value;
          }
          onChanged();
        } else {
          endTimeBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp endTime = 5;</code>
       */
      public Builder clearEndTime() {
        if (endTimeBuilder_ == null) {
          endTime_ = null;
          onChanged();
        } else {
          endTime_ = null;
          endTimeBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp endTime = 5;</code>
       */
      public com.google.protobuf.Timestamp.Builder getEndTimeBuilder() {
        
        onChanged();
        return getEndTimeFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp endTime = 5;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getEndTimeOrBuilder() {
        if (endTimeBuilder_ != null) {
          return endTimeBuilder_.getMessageOrBuilder();
        } else {
          return endTime_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : endTime_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp endTime = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getEndTimeFieldBuilder() {
        if (endTimeBuilder_ == null) {
          endTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getEndTime(),
                  getParentForChildren(),
                  isClean());
          endTime_ = null;
        }
        return endTimeBuilder_;
      }

      private int day_ = 0;
      /**
       * <code>.ScheduleSlot.Day day = 6;</code>
       * @return The enum numeric value on the wire for day.
       */
      @java.lang.Override public int getDayValue() {
        return day_;
      }
      /**
       * <code>.ScheduleSlot.Day day = 6;</code>
       * @param value The enum numeric value on the wire for day to set.
       * @return This builder for chaining.
       */
      public Builder setDayValue(int value) {
        
        day_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.ScheduleSlot.Day day = 6;</code>
       * @return The day.
       */
      @java.lang.Override
      public ScheduleProto.ScheduleSlot.Day getDay() {
        @SuppressWarnings("deprecation")
        ScheduleProto.ScheduleSlot.Day result = ScheduleProto.ScheduleSlot.Day.valueOf(day_);
        return result == null ? ScheduleProto.ScheduleSlot.Day.UNRECOGNIZED : result;
      }
      /**
       * <code>.ScheduleSlot.Day day = 6;</code>
       * @param value The day to set.
       * @return This builder for chaining.
       */
      public Builder setDay(ScheduleProto.ScheduleSlot.Day value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        day_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.ScheduleSlot.Day day = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearDay() {
        
        day_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ScheduleSlot)
    }

    // @@protoc_insertion_point(class_scope:ScheduleSlot)
    private static final ScheduleProto.ScheduleSlot DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ScheduleProto.ScheduleSlot();
    }

    public static ScheduleProto.ScheduleSlot getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ScheduleSlot>
        PARSER = new com.google.protobuf.AbstractParser<ScheduleSlot>() {
      @java.lang.Override
      public ScheduleSlot parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ScheduleSlot(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ScheduleSlot> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ScheduleSlot> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ScheduleProto.ScheduleSlot getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Schedule_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Schedule_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ScheduleSlot_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ScheduleSlot_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022simschedular.proto\032\037google/protobuf/ti" +
      "mestamp.proto\"V\n\010Schedule\022\022\n\npersonName\030" +
      "\001 \001(\t\022\030\n\020scheduleRevision\030\002 \001(\t\022\034\n\005slots" +
      "\030\003 \003(\0132\r.ScheduleSlot\"\200\002\n\014ScheduleSlot\022\n" +
      "\n\002ID\030\001 \001(\005\022\020\n\010slotName\030\002 \001(\t\022\020\n\010slotDesc" +
      "\030\003 \001(\t\022-\n\tstartTime\030\004 \001(\0132\032.google.proto" +
      "buf.Timestamp\022+\n\007endTime\030\005 \001(\0132\032.google." +
      "protobuf.Timestamp\022\036\n\003day\030\006 \001(\0162\021.Schedu" +
      "leSlot.Day\"D\n\003Day\022\007\n\003MON\020\000\022\007\n\003TUE\020\001\022\007\n\003W" +
      "ED\020\002\022\007\n\003THU\020\003\022\007\n\003FRI\020\004\022\007\n\003SAT\020\005\022\007\n\003SUN\020\006" +
      "B\017B\rScheduleProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_Schedule_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Schedule_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Schedule_descriptor,
        new java.lang.String[] { "PersonName", "ScheduleRevision", "Slots", });
    internal_static_ScheduleSlot_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ScheduleSlot_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ScheduleSlot_descriptor,
        new java.lang.String[] { "ID", "SlotName", "SlotDesc", "StartTime", "EndTime", "Day", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
